import { NgClass, NgStyle } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-movies-list',
  imports: [NgClass,NgStyle],
  templateUrl: './movies-list.component.html',
  styleUrl: './movies-list.component.css',
})
export class MoviesListComponent {
  // allMovies:any[]=[]
  allMovies = [
    {
      adult: false,
      backdrop_path: '/mEW9XMgYDO6U0MJcIRqRuSwjzN5.jpg',
      genre_ids: [28, 53],
      id: 1007734,
      original_language: 'en',
      original_title: 'Nobody 2',
      overview:
        'Former assassin Hutch Mansell takes his family on a nostalgic vacation to a small-town theme park, only to be pulled back into violence when they clash with a corrupt operator, a crooked sheriff, and a ruthless crime boss.',
      popularity: 410.2669,
      poster_path: '/svXVRoRSu6zzFtCzkRsjZS7Lqpd.jpg',
      release_date: '2025-08-13',
      title: 'Nobody 2',
      video: false,
      vote_average: 7.12,
      vote_count: 189,
    },
    {
      adult: false,
      backdrop_path: '/1wi1hcbl6KYqARjdQ4qrBWZdiau.jpg',
      genre_ids: [28, 35, 80],
      id: 1035259,
      original_language: 'en',
      original_title: 'The Naked Gun',
      overview:
        'Only one man has the particular set of skills... to lead Police Squad and save the world: Lt. Frank Drebin Jr.',
      popularity: 396.1781,
      poster_path: '/aq0JMbmSfPwG8JvAzExJPrBHqmG.jpg',
      release_date: '2025-07-30',
      title: 'The Naked Gun',
      video: false,
      vote_average: 6.851,
      vote_count: 338,
    },
    {
      adult: false,
      backdrop_path: '/xSD0q1FiuZkvHuy7uscOLbmd1hR.jpg',
      genre_ids: [12, 28, 14],
      id: 13494,
      original_language: 'en',
      original_title: 'Red Sonja',
      overview:
        'A young girl rises from the ashes of tragedy to become the most feared warrior woman of all time: the She-Devil with a Sword.',
      popularity: 318.308,
      poster_path: '/l10eghFN1nQmWwMSt91MlLvZZFA.jpg',
      release_date: '2025-07-31',
      title: 'Red Sonja',
      video: false,
      vote_average: 5.9,
      vote_count: 56,
    },
    {
      adult: false,
      backdrop_path: '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
      genre_ids: [16, 28, 14, 53],
      id: 1311031,
      original_language: 'ja',
      original_title: '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
      overview:
        'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
      popularity: 310.3214,
      poster_path: '/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg',
      release_date: '2025-07-18',
      title: 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
      video: false,
      vote_average: 7.3,
      vote_count: 100,
    },
    {
      adult: false,
      backdrop_path: '/fBlzTwgtbDYkDKlhnPu69jHfVGy.jpg',
      genre_ids: [27, 10749],
      id: 1242011,
      original_language: 'en',
      original_title: 'Together',
      overview:
        "With a move to the countryside already testing the limits of a couple's relationship, a supernatural encounter begins an extreme transformation of their love, their lives, and their flesh.",
      popularity: 305.6738,
      poster_path: '/6MJxjNxjgAtuBEOVYtuF4yUYXZC.jpg',
      release_date: '2025-07-23',
      title: 'Together',
      video: false,
      vote_average: 7.134,
      vote_count: 354,
    },
    {
      adult: false,
      backdrop_path: '/zNriRTr0kWwyaXPzdg1EIxf0BWk.jpg',
      genre_ids: [878, 12, 28],
      id: 1234821,
      original_language: 'en',
      original_title: 'Jurassic World Rebirth',
      overview:
        "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
      popularity: 304.4567,
      poster_path: '/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg',
      release_date: '2025-07-01',
      title: 'Jurassic World Rebirth',
      video: false,
      vote_average: 6.38,
      vote_count: 1945,
    },
    {
      adult: false,
      backdrop_path: '/8jeDyvFQKgss36FbGAmGQVzPXlH.jpg',
      genre_ids: [53, 28, 35],
      id: 1151334,
      original_language: 'en',
      original_title: 'Eenie Meanie',
      overview:
        'A former teenage getaway driver gets dragged back into her unsavory past when a former employer offers her a chance to save the life of her chronically unreliable ex-boyfriend.',
      popularity: 265.9985,
      poster_path: '/12Va3oO3oYUdOd75zM57Nx1976a.jpg',
      release_date: '2025-08-21',
      title: 'Eenie Meanie',
      video: false,
      vote_average: 6.458,
      vote_count: 142,
    },
    {
      adult: false,
      backdrop_path: '/gVPjIcYo1gTaACF43OMsralrcUS.jpg',
      genre_ids: [27, 9648, 53, 28, 12],
      id: 1083433,
      original_language: 'en',
      original_title: 'I Know What You Did Last Summer',
      overview:
        "When five friends inadvertently cause a deadly car accident, they cover up their involvement and make a pact to keep it a secret rather than face the consequences. A year later, their past comes back to haunt them and they're forced to confront a horrifying truth: someone knows what they did last summer…and is hell-bent on revenge.",
      popularity: 248.9251,
      poster_path: '/A06yXys3hrCWu8xiNoHCFLTG5SH.jpg',
      release_date: '2025-07-16',
      title: 'I Know What You Did Last Summer',
      video: false,
      vote_average: 5.9,
      vote_count: 288,
    },
    {
      adult: false,
      backdrop_path: '/jvpkBenB6hv19WWYVlaiow8zklq.jpg',
      genre_ids: [16, 10751, 35, 80, 12],
      id: 1175942,
      original_language: 'en',
      original_title: 'The Bad Guys 2',
      overview:
        'The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.',
      popularity: 230.8286,
      poster_path: '/5DJbIWxIotQYUnRrRGhSxjxmvye.jpg',
      release_date: '2025-07-24',
      title: 'The Bad Guys 2',
      video: false,
      vote_average: 7.8,
      vote_count: 300,
    },
    {
      adult: false,
      backdrop_path: '/AeDzjt00Hfh9CuW7TIUdYBJmWYM.jpg',
      genre_ids: [14, 10751, 28, 12],
      id: 1087192,
      original_language: 'en',
      original_title: 'How to Train Your Dragon',
      overview:
        'On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.',
      popularity: 213.9403,
      poster_path: '/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg',
      release_date: '2025-06-06',
      title: 'How to Train Your Dragon',
      video: false,
      vote_average: 8,
      vote_count: 1815,
    },
    {
      adult: false,
      backdrop_path: '/w3Bi0wygeFQctn6AqFTwhGNXRwL.jpg',
      genre_ids: [16, 10402, 14, 35],
      id: 803796,
      original_language: 'en',
      original_title: 'KPop Demon Hunters',
      overview:
        "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
      popularity: 212.6593,
      poster_path: '/22AouvwlhlXbe3nrFcjzL24bvWH.jpg',
      release_date: '2025-06-20',
      title: 'KPop Demon Hunters',
      video: false,
      vote_average: 8.379,
      vote_count: 1243,
    },
    {
      adult: false,
      backdrop_path: '/Q2OajDi2kcO6yErb1IAyVDTKMs.jpg',
      genre_ids: [27, 9648],
      id: 1078605,
      original_language: 'en',
      original_title: 'Weapons',
      overview:
        'When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.',
      popularity: 180.903,
      poster_path: '/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg',
      release_date: '2025-08-04',
      title: 'Weapons',
      video: false,
      vote_average: 7.466,
      vote_count: 743,
    },
    {
      adult: false,
      backdrop_path: '/4KN06gns94rQFoYQWDGunK7Cob4.jpg',
      genre_ids: [35, 9648, 80],
      id: 744653,
      original_language: 'en',
      original_title: 'The Thursday Murder Club',
      overview:
        'A group of senior sleuths passionate about solving cold cases get plunged into a real-life murder mystery in this comic crime caper.',
      popularity: 162.8337,
      poster_path: '/tzrJulItjttxzoX0t3B2My46TS7.jpg',
      release_date: '2025-08-22',
      title: 'The Thursday Murder Club',
      video: false,
      vote_average: 6.733,
      vote_count: 275,
    },
    {
      adult: false,
      backdrop_path: '/IOEXDwaVH2IcSXIZhCg7g572ic.jpg',
      genre_ids: [27, 9648, 53],
      id: 926606,
      original_language: 'en',
      original_title: 'The Home',
      overview:
        'A troubled man starts working at a retirement home and realizes its residents and caretakers harbor sinister secrets. As he investigates the building and its forbidden fourth floor, he starts to uncover connections to his own past and upbringing as a foster child.',
      popularity: 153.8506,
      poster_path: '/qyGY1k5GqAORsVhfZA3gFKirZWD.jpg',
      release_date: '2025-07-24',
      title: 'The Home',
      video: false,
      vote_average: 6.603,
      vote_count: 34,
    },
    {
      adult: false,
      backdrop_path: '/kYsU56QEcwEr8jAQ6Vm3M8bXTWz.jpg',
      genre_ids: [28, 35, 18, 37],
      id: 1429739,
      original_language: 'th',
      original_title: 'เขาชุมทอง คะนองชุมโจร',
      overview:
        'At the tail end of World War II, a bandit leader and his crew go up against his sworn enemy and the Japanese army to rob a train full of gold.',
      popularity: 152.6919,
      poster_path: '/7j6jZNhCTnsZy5QItpruDwyBWoo.jpg',
      release_date: '2025-08-19',
      title: 'Gold Rush Gang',
      video: false,
      vote_average: 6.763,
      vote_count: 19,
    },
    {
      adult: false,
      backdrop_path: '/mOcMPfCJEvSREq8OZzg42gFgrGt.jpg',
      genre_ids: [10749, 53],
      id: 1300116,
      original_language: 'de',
      original_title: 'Fall for Me',
      overview:
        "Lilli is suspicious of her sister's new fiance, but when an attractive stranger enters her life, she's suddenly distracted by the thralls of desire.",
      popularity: 152.6592,
      poster_path: '/nLTs9SNBuk3DuB8D0p3mSsPYN7J.jpg',
      release_date: '2025-08-20',
      title: 'Fall for Me',
      video: false,
      vote_average: 6.136,
      vote_count: 81,
    },
    {
      adult: false,
      backdrop_path: '/9DYFYhmbXRGsMhfUgXM3VSP9uLX.jpg',
      genre_ids: [27],
      id: 1038392,
      original_language: 'en',
      original_title: 'The Conjuring: Last Rites',
      overview:
        'Paranormal investigators Ed and Lorraine Warren take on one last terrifying case involving mysterious entities they must confront.',
      popularity: 145.5598,
      poster_path: '/8XfIKOPmuCZLh5ooK13SPKeybWF.jpg',
      release_date: '2025-09-03',
      title: 'The Conjuring: Last Rites',
      video: false,
      vote_average: 7.7,
      vote_count: 15,
    },
    {
      adult: false,
      backdrop_path: '/ySHUoK4utUOiSfCinw81H1TsV0E.jpg',
      genre_ids: [878, 28, 27],
      id: 1241470,
      original_language: 'en',
      original_title: 'Osiris',
      overview:
        'Special Forces commandos on a mission are abducted mid-operation by a mysterious spacecraft. Upon waking aboard, they find themselves prey to a relentless alien race in a fight for survival.',
      popularity: 137.8014,
      poster_path: '/3YtZHtXPNG5AleisgEatEfZOT2w.jpg',
      release_date: '2025-07-25',
      title: 'Osiris',
      video: false,
      vote_average: 6.695,
      vote_count: 110,
    },
    {
      adult: false,
      backdrop_path: '/dcLV5rEXuQRW0ZlB7IMLArHMyWh.jpg',
      genre_ids: [35, 14, 10751],
      id: 1125257,
      original_language: 'en',
      original_title: 'Freakier Friday',
      overview:
        'Years after Tess and Anna endured an identity crisis, Anna now has a daughter of her own and a soon-to-be stepdaughter. As they navigate the myriad challenges that come when two families merge, Tess and Anna discover lightning might indeed strike twice.',
      popularity: 135.0137,
      poster_path: '/9wV65OmsjLAqBfDnYTkMPutXH8j.jpg',
      release_date: '2025-08-06',
      title: 'Freakier Friday',
      video: false,
      vote_average: 6.899,
      vote_count: 154,
    },
    {
      adult: false,
      backdrop_path: '/nZsKWhwhUL3Eg88SkIaJjuIZzpN.jpg',
      genre_ids: [28, 35, 53],
      id: 1319895,
      original_language: 'en',
      original_title: 'Hostile Takeover',
      overview:
        'Follows Pete, a professional hitman, as he faces a group of assassins after the boss of a crime syndicate suspects disloyalty due to his attendance at Workaholics Anonymous meetings.',
      popularity: 123.1804,
      poster_path: '/vntwlS3CAKfoLTs90GaoK6lymBC.jpg',
      release_date: '2025-08-08',
      title: 'Hostile Takeover',
      video: false,
      vote_average: 7.32,
      vote_count: 25,
    },
  ];
}
